name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

# Builds images for target boards.
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16.x]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.JS ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Update yarn and npm
        run: npm i -g yarn npm
      - name: Enable workspaces
        run: yarn config set workspaces-experimental true
      - name: Install and build chonky
        run: cd ./packages/chonky && yarn install
      - name: Install and build chonky-icon-fontawesome
        run: cd ./packages/chonky-icon-fontawesome && yarn install
